### ISSUE TITLE
it is missing bower.json file.

### ISSUE THREAD

**Issue by publicocean0** [entraigas/jstz#1]
it is impossible to load main file. 
every bower package need to add bower.json

**Comment by entraigas** [comment]
Sorry, but there's no support for bower (and no plan to add it).
Please feel free to fork the project and add a bower.json file.

**Comment by publicocean0** [comment]
so then remove it in bower repository , it creates confusion

**Comment by entraigas** [comment]
That's weird, I never add it to the bower repository...
Can you send me the link?
