### ISSUE TITLE
How to use in typescript?

### ISSUE THREAD

**Issue by bhargav-sae** [entraigas/jstz#4]
It is saying `jstz.d.ts` is not a module.

**Comment by entraigas** [comment]
Hi, the code it's pretty old and wasn't designed to be compatible with typescript.
And sorry but -for now- have no plan for update it to typescript neither...

**Comment by bhargav-sae** [comment]
> Hi, the code it's pretty old and wasn't designed to be compatible with typescript.
> And sorry but -for now- have no plan for update it to typescript neither...

Actually nvm. Its just giving you an error on editor But I found a workout. You can close it.
